name: Build and Test on ci-implementation branch

on:
  push:
    branches:
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Decrypt the keystore file
        uses: docker://opengg/gpg
        with:
          args: -d --quiet --batch --passphrase  ${{ secrets.GPG_PASSWORD }} --output keystore.p12 ${{ secrets.GPG_KEY_FILE }}

      - name: Decrypt the keystore.properties file
          uses: docker://opengg/gpg
          with:
            args: -d --quiet --batch --passphrase ${{ secrets.GPG_PASSWORD }} --output keystore.properties ${{ secrets.GPG_KEYSTORE_PROPERTIES_FILE }}

      - name: Build with Gradle
        run: ./gradlew assembleRelease -P keystore.properties

      - name: Test with Gradle
        run: ./gradlew test
