name: Build and Test on ci-implementation branch

on:
  push:
    branches:
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Decrypt the keystore file
        run: |
          echo "${{ secrets.GPG_KEY_FILE }}" | base64 --decode | gpg --quiet --batch --no-tty --passphrase "${{ secrets.GPG_PASSWORD }}" --output keystore.p12 --decrypt --armor

      - name: Decrypt the keystore.properties file
        run: |
          echo "${{ secrets.GPG_KEYSTORE_PROPERTIES_FILE }}" | base64 --decode | gpg --quiet --batch --no-tty --passphrase "${{ secrets.GPG_PASSWORD }}" --output keystore.properties --decrypt

      - name: Decrypt the google-services.json file
        run: |
          echo "${{ secrets.GPG_GOOGLE_SERVICES_JSON_FILE }}" | base64 --decode | gpg --quiet --batch --no-tty --passphrase "${{ secrets.GPG_PASSWORD }}" --output app/google-services.json --decrypt

      - name: Build with Gradle
        run: ./gradlew assembleRelease -P keystore.properties

      - name: Test with Gradle
        run: ./gradlew test

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Distribute to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups internal-testers
